In [5]:
import numpy as np

In [27]:
x = np.random.randint(1, 100, size=100)

In [28]:
z = np.random.randint(-100, 100, size=100)

In [29]:
epsilon = np.random.randn(100)

In [30]:
y = x **2 + x * 3 + 1/x + 2 * z**3 + epsilon

In [32]:
x

array([13, 94, 91,  3, 86, 69, 75, 48, 74, 65, 60, 45, 35, 32, 88, 61, 98,
       76, 80,  5, 97, 82, 65, 23, 68,  3, 23, 28, 38, 86, 58, 35, 28, 49,
       22, 94, 49, 54, 95, 97, 80, 93, 37, 60, 91,  5,  9,  4, 58, 82,  5,
       92, 28, 39, 86, 88, 28, 55, 89, 46, 92, 37, 85, 23, 27, 82, 46, 19,
       21,  7, 11, 91, 82, 25, 92, 49, 67, 58, 87, 48, 10, 33, 71, 42, 76,
       72, 48, 24, 31, 39, 21, 20, 82, 63, 86, 12, 63, 14, 55, 40])

In [33]:
z

array([-85,  75,   3, -61,  98,  12,  17,  -7,  77, -10, -72, -28, -40,
        12, -78,  29,  99, -18, -88,  40, -53, -38,  -1, -71,  13,  60,
       -10, -47,  54, -36,  -8, -94, -44,  18,  81, -14,  11, -44,  85,
        25,  -6,  44, -76,  80,  30,  -6,  48, -84,  91,  50,  92, -92,
       -13,  30,  50, -10,  81,  74, -50, -82,  41, -21,  70,  98,  56,
        38,  74,  50,  64, -54, -87,  17,  -8, -23,   7, -94,  90, -41,
        56, -10,   4, -49, -82, -42,  88,  40, -64, -22,   6, -78,   2,
       -27, -88, -94,   6, -29,  83, -29, -37, -16])

In [31]:
y

array([-1.22803989e+06,  8.52867526e+05,  8.60899636e+03, -4.53943853e+05,
        1.89003685e+06,  8.42493182e+03,  1.56757582e+04,  1.76245315e+03,
        9.18763585e+05,  2.41816992e+03, -7.42715411e+05, -4.17434209e+04,
       -1.26669342e+05,  4.57731239e+03, -9.41096063e+05,  5.26811806e+04,
        1.95049465e+06, -5.65941723e+03, -1.35630461e+06,  1.28039290e+05,
       -2.88054611e+05, -1.02773305e+05,  4.41709037e+03, -7.15223491e+05,
        9.22239262e+03,  4.32016959e+05, -1.40385186e+03, -2.06779022e+05,
        3.16487341e+05, -8.56589801e+04,  2.51321935e+03, -1.65983576e+06,
       -1.69500947e+05,  1.42124704e+04,  1.06343086e+06,  3.62890086e+03,
        5.21179859e+03, -1.67291101e+05,  1.23755975e+06,  4.09504616e+04,
        6.20754304e+03,  1.79296627e+05, -8.76473004e+05,  1.02777994e+06,
        6.25513168e+04, -3.91607654e+02,  2.21292834e+05, -1.18538134e+06,
        1.51067994e+06,  2.56971343e+05,  1.55741518e+06, -1.54863542e+06,
       -3.52224178e+03,  

In [34]:
x_test = np.random.randint(1, 100, size=100)
z_test = np.random.randint(-100, 100, size=100)
y_test = x_test **2 + x_test * 3 + 1/x_test + 2 * z_test**3

In [35]:
x_test

array([84, 90, 23, 85, 18, 37, 58,  6, 30, 43, 30, 65, 13, 81, 73, 82, 51,
       86, 14, 65, 20, 34, 62, 56, 89, 56, 55, 93, 60, 62, 22, 39, 79, 49,
       33, 79,  8, 77,  2,  4, 65,  1, 79, 91,  7, 32, 71,  4, 10, 21,  4,
       11, 55, 38, 12, 38, 54, 60, 61, 48, 29, 89, 13, 16, 62,  5, 32, 28,
       86, 50, 78, 11, 50, 75, 58, 76, 52, 63, 97, 48, 64, 51, 33, 75, 88,
       46, 25, 46, 64, 97, 21, 32, 88, 64, 21, 64, 46, 23, 73, 14])

In [14]:
y_test

array([-3.89625957e+05, -1.81952381e+02, -4.15797143e+03,  1.88763801e+06,
       -4.06469984e+05, -1.26201399e+06,  9.88428021e+05, -1.02183998e+06,
        1.40997820e+06, -3.47073984e+05,  8.08038462e+02,  1.21942018e+05,
        8.79282029e+05, -2.44889986e+05, -1.01525999e+06, -1.10270775e+06,
        1.20800217e+04,  9.19070013e+05, -1.18133952e+05, -4.09703968e+05,
       -1.03265987e+05, -2.74979884e+04, -6.55963968e+05,  1.06315207e+06,
       -1.99935196e+06,  3.25001786e+03, -5.63950000e+02,  8.05860233e+04,
        1.00601389e+03, -3.29995980e+05,  1.55901403e+06, -6.27935966e+05,
       -2.72661989e+05,  3.40404012e+05, -9.46849978e+05,  5.51698021e+05,
        2.68606018e+05,  8.78022143e+05,  1.06444003e+06,  1.59042250e+05,
        7.76041667e+02,  1.73122020e+05, -1.23171985e+05,  4.09001695e+03,
        1.94114805e+06, -9.01596296e+03, -1.65990997e+06,  7.56196010e+05,
        1.36492202e+06, -1.88217592e+06,  1.06353004e+06,  3.25220112e+04,
        2.26584014e+05,  

In [15]:
def y_func(x, z):
    return x **2 + x * 3 + 1/x + 2 * z**3

In [26]:
y_func(5, 1)

42.2

-389625.957